CREATE TABLE IF NOT EXISTS conversation_message_attachments (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  attachment_id VARCHAR(80) NOT NULL,
  message_id VARCHAR(80) NOT NULL,
  conversation_id VARCHAR(64) NOT NULL,
  name VARCHAR(255) NOT NULL,
  mime_type VARCHAR(128) DEFAULT NULL,
  type VARCHAR(24) NOT NULL,
  size BIGINT NOT NULL DEFAULT 0,
  url VARCHAR(1024) NOT NULL,
  object_key VARCHAR(512) DEFAULT NULL,
  thumbnail_url VARCHAR(1024) DEFAULT NULL,
  hash VARCHAR(128) DEFAULT NULL,
  status VARCHAR(16) NOT NULL DEFAULT 'done',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_conversation_message_attachments_attachment_id (attachment_id),
  KEY idx_conversation_message_attachments_message_id (message_id),
  KEY idx_conversation_message_attachments_conversation_id (conversation_id),
  CONSTRAINT fk_conversation_message_attachments_message_id FOREIGN KEY (message_id) REFERENCES conversation_messages(message_id),
  CONSTRAINT fk_conversation_message_attachments_conversation_id FOREIGN KEY (conversation_id) REFERENCES conversations(conversation_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
